# Generated by Django 3.2 on 2021-04-30 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UID', 'FID')},
            },
        ),
    ]
