# Generated by Django 3.2 on 2021-05-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_friends_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Users.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='Users.post'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
