# Generated by Django 3.2 on 2021-04-30 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024)),
                ('Time', models.DateField(auto_now_add=True)),
                ('postImg', models.ImageField(blank=True, null=True, upload_to='')),
                ('group_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.group')),
                ('poster_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liked_post', to='Users.post')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likerID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UID', 'PID')},
            },
        ),
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Group', to='Users.group')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UID', 'GID')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField(auto_now_add=True)),
                ('content', models.TextField(max_length=1024)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to='Users.post')),
            ],
            options={
                'unique_together': {('UID', 'postID', 'Time')},
            },
        ),
    ]
