# Generated by Django 3.2 on 2021-04-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_comment_group_join_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='group_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.group'),
        ),
    ]
