# Generated by Django 3.2 on 2021-04-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('Users', '0005_auto_20210430_2134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='join',
            name='GID',
        ),
        migrations.RemoveField(
            model_name='join',
            name='UID',
        ),
        migrations.AlterField(
            model_name='post',
            name='group_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='join',
        ),
    ]
