# Generated by Django 3.2 on 2021-05-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_join_gid'),
        ('Users', '0006_auto_20210430_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
