# Generated by Django 3.2 on 2021-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210430_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
