# Generated by Django 3.2 on 2021-05-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_message_time'),
        ('Users', '0007_alter_post_group_id'),
    ]

    operations = [
    ]
