# Generated by Django 3.2 on 2021-05-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210430_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.TextField(default='chat', max_length=20),
            preserve_default=False,
        ),
    ]
