# Generated by Django 3.2 on 2021-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_number_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100, null=True),
        ),
    ]
