# Generated by Django 3.2 on 2021-05-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='GID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group', to='groups.group'),
        ),
    ]
