# Generated by Django 3.2 on 2021-05-02 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0008_alter_join_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='UID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
